### ISSUE TITLE
Uncaught ReferenceError: $screen is not defined

### ISSUE THREAD

**Issue by francoislevesque** [alpine-collective/toolkit#7]
Using alpine js 3 via a CDN.

We are importing files like this:

```
<script src="//unpkg.com/alpinejs" defer></script>
<script src="//unpkg.com/@alpine-collective/toolkit-screen@1.0.0/dist/cdn.min.js" defer></script>
```

When using `$screen('md')`, we get this error:

```
Alpine Expression Error: $screen is not defined
Expression: "$screen('md')"
Uncaught ReferenceError: $screen is not defined
```

**Comment by SimoTod** [comment]
Sorry, I've just seen this issue after ages (Better late than never, they say :D ). 
You probably figured it out already but plugins need to be imported before Alpine.
