### ISSUE TITLE
Including toolkit plugin throws error

### ISSUE THREAD

**Issue by codedge** [alpine-collective/toolkit#8]
I am using the toolkit with Alpine `3.10.2` like this

```js
import Alpine from 'alpinejs'
import Toolkit from '@alpine-collective/toolkit'
import GLightbox from 'glightbox';
import $ from 'jquery';
import 'slick-carousel';

Alpine.plugin(Toolkit)
Alpine.start()
```

but I am getting an error on the console saying

```
Uncaught TypeError: e is not a function
    plugin https://villa-brocante-statamic.test/js/site.js?id=6a69235128732592cb4494ded2351745:2
    218 https://villa-brocante-statamic.test/js/site.js?id=6a69235128732592cb4494ded2351745:2
    n https://villa-brocante-statamic.test/js/site.js?id=6a69235128732592cb4494ded2351745:2
    <anonymous> https://villa-brocante-statamic.test/js/site.js?id=6a69235128732592cb4494ded2351745:2
    O https://villa-brocante-statamic.test/js/site.js?id=6a69235128732592cb4494ded2351745:2
    <anonymous> https://villa-brocante-statamic.test/js/site.js?id=6a69235128732592cb4494ded2351745:2
    <anonymous> https://villa-brocante-statamic.test/js/site.js?id=6a69235128732592cb4494ded2351745:2
[site.js:2:24366](https://villa-brocante-statamic.test/js/site.js?id=6a69235128732592cb4494ded2351745)
```

<img width="1672" alt="grafik" src="https://user-images.githubusercontent.com/4409904/167031028-d3bffa16-d2cb-48e9-a051-fa45e03a496d.png">

This happens with `yarn run production`.

When running `yarn run dev` I get this error

<img width="1674" alt="grafik" src="https://user-images.githubusercontent.com/4409904/167033585-98893247-16bf-49cf-9626-822faeaa7f74.png">

which leads me to this place

<img width="493" alt="grafik" src="https://user-images.githubusercontent.com/4409904/167033628-6baf40e4-e58e-4e1c-a2fd-326ef94e190d.png">

Any idea what is wrong there?

**Comment by iautom8things** [comment]
Thank you for posting this question.  I struggle with JS package management so when I hit this same issue it was reassuring to know that it wasn't _just me_.

From what I can tell, it seems like there's something wrong with the ordering of the files that are combined with the NPM distribution of alpinejs.
<img width="215" alt="Screen Shot 2022-07-10 at 10 01 05 AM" src="https://user-images.githubusercontent.com/522040/178150416-c8f2fb90-c358-474d-88f3-3c170535b4c7.png">
<img width="225" alt="Screen Shot 2022-07-10 at 10 00 56 AM" src="https://user-images.githubusercontent.com/522040/178150417-cb1d2594-a955-4ead-b527-13fe58d1e459.png">

For some reason `packages/alpinejs/src/plugin.js` is included _before_ `packages/alpinejs/src/alpine.js` and so a reference to `alpine_default` is used before it's defined.

Unfortunately, this is the extent of my JS knowledge.  I can try to open up an issue on the main repo and see if they can help.

**Comment by benkoshy** [comment]
Having the same issue. not sure how to fix it: 

![image](https://user-images.githubusercontent.com/15097447/180701546-793cba1c-cd3e-4dc9-b186-1e9775370223.png)

**Comment by goxmedia** [comment]
Same issue here. Any update on a fix so we can keep the bundle in-tact?

<img width="624" alt="Screen Shot 2022-08-31 at 3 57 47 PM" src="https://user-images.githubusercontent.com/89282/187799663-105d52c4-6c9c-482f-b20e-43a5e74a0fa9.png">

<img width="467" alt="Screen Shot 2022-08-31 at 3 57 23 PM" src="https://user-images.githubusercontent.com/89282/187799680-660da1dc-a001-499d-870e-5f3082ffd637.png">

**Comment by KevinBatdorf** [comment]
Hey, if you `console.log(Toolkit)` what shows? is it a function? 

Toolkit is being passed in to [Alpine.plugin](https://github.com/alpinejs/alpine/blob/main/packages/alpinejs/src/plugin.js#L3) which invokes it as the parameter named `callback`. The error is suggesting that `Toolkit`, the callback, is not a function. However, Toolkit is exporting a default function [here](https://github.com/alpine-collective/toolkit/blob/main/packages/%24interval/src/index.js#L1).

I'm personally not super active with Alpine these days but I'm happy to test it out this weekend and maybe we can get this figured out (also, sorry for not being super responsive here)

**Comment by goxmedia** [comment]
@KevinBatdorf Sorry for my late reply here. Must have missed your response. See the below. Looks like both come back as undefined.

<img width="713" alt="Screenshot 2022-11-13 at 8 57 09 PM" src="https://user-images.githubusercontent.com/89282/201580007-43354127-d5bf-4c1d-9114-6048b60bbd1e.png">
<img width="487" alt="Screenshot 2022-11-13 at 8 57 35 PM" src="https://user-images.githubusercontent.com/89282/201580010-3ba1a969-796c-4f9c-91a8-ef7f0187c62f.png">
<img width="487" alt="Screenshot 2022-11-13 at 8 57 57 PM" src="https://user-images.githubusercontent.com/89282/201580013-afae2581-4a90-4ea1-a583-aa74c4b8c353.png">
<img width="487" alt="Screenshot 2022-11-13 at 9 05 26 PM" src="https://user-images.githubusercontent.com/89282/201580016-261c3505-395f-4d31-88be-89d3883dbada.png">

**Comment by KevinBatdorf** [comment]
Are the files there in `node_modules`? I wouldn't expect the console to be able to log it there, but you could try on line 13 to console.log it. 

Just to confirm, you ran `npm install @alpine-collective/toolkit-interval --save-dev` right? And not simply `@alpine-collective/toolkit`?

**Comment by goxmedia** [comment]
I just ran yarn install on my package-json file which you can see from the snippets earlier in this thread. Tried both `"@alpine-collective/toolkit-truncate": "^1.0.1"` and `"@alpine-collective/toolkit-truncate": "^1.0.1"` with the same issue.

**Comment by goxmedia** [comment]
Sorry, and yes, the files are located in `node_modules`.

**Comment by goxmedia** [comment]
Here's a snapshot of of the package within the node_modules directory:

<img width="487" alt="Screenshot 2022-11-14 at 12 03 04 PM" src="https://user-images.githubusercontent.com/89282/201754837-3deea7b6-5e3a-4f7a-abb9-5e0ba04d99c4.png">

**Comment by goxmedia** [comment]
And here is the trace from the console when clicking on the `moduie.esm.js:1372:1` error above:

<img width="487" alt="Screenshot 2022-11-14 at 12 07 09 PM" src="https://user-images.githubusercontent.com/89282/201755514-5c8263e3-cc88-41e9-9d37-337e791e3805.png">

**Comment by KevinBatdorf** [comment]
Can you try `Alpine.plugin(Toolkit.default)`?

**Comment by KevinBatdorf** [comment]
Sorry, `Alpine.plugin(Truncate.default)`

**Comment by goxmedia** [comment]
Thanks. No change. Same errors.

**Comment by SimoTod** [comment]
Fixed in 1.0.2

**Comment by goxmedia** [comment]
Yes, it is now fixed in v1.02. What was the issue (and thanks for the quick fix)?

**Comment by SimoTod** [comment]
The browser field (well, the wrong value I did put in that field) was confusing webpack that was trying to use the cdn build (which doesn't export anything) inside the bundle.

**Comment by goxmedia** [comment]
Goit it. Thanks again Simone. Take it easy.
